-- phpMyAdmin SQL Dump
-- version 4.8.0.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Sep 14, 2018 at 11:08 PM
-- Server version: 10.1.32-MariaDB
-- PHP Version: 7.2.5

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `emrg_doc`
--

-- --------------------------------------------------------

--
-- Table structure for table `diagonistic_test`
--

CREATE TABLE `diagonistic_test` (
  `Id` int(11) NOT NULL,
  `Test_Name` varchar(200) NOT NULL,
  `Lab` text NOT NULL,
  `Cost` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `doctor`
--

CREATE TABLE `doctor` (
  `Id` int(11) NOT NULL,
  `Name` varchar(100) NOT NULL,
  `Specialities` varchar(200) NOT NULL,
  `Degree` text NOT NULL,
  `Email` varchar(100) NOT NULL,
  `Phone` varchar(20) NOT NULL,
  `Fees` int(11) NOT NULL,
  `image` varchar(1000) NOT NULL,
  `background` text NOT NULL,
  `time` varchar(100) NOT NULL,
  `chember` varchar(100) NOT NULL,
  `day` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `doctor`
--

INSERT INTO `doctor` (`Id`, `Name`, `Specialities`, `Degree`, `Email`, `Phone`, `Fees`, `image`, `background`, `time`, `chember`, `day`) VALUES
(1, 'Professor Dr. Md. Ayub Ali Chowdhury', 'Allergists', 'bangladesh medical college\r\nhspc, mbbs,(hrpce )', 'Ayub.Ali@gmail.com', '9126625-6, ', 1000, 'images/Allergists.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '05.00PM to 09.00 PM', 'Shahid Suhrawardy Hospital', 'Sat,Mon,Fri'),
(2, 'Professor Dr. Md. Abdus Sobur', 'Allergists', 'MBBS, FCPS\r\n\r\n Professor & Head of the Department \r\n Ibn Sina Medical College Hospital \r\nDepartment Name:Medicine', 'Abdus.Sobur@gmail.com', '01917289967', 1000, 'images/Dermatologists.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '05.00PM to 09.00 PM', 'United Hospital Limited', 'Sat,Tue,Fri'),
(3, 'Professor Dr. Md. Azizul Haque', 'Medicine Specialists', '  MBBS, MCPS, MD\r\n Ibn Sina Medical College Hospital \r\n Department Name:Medicine', 'Azizul.Haque@gmail.com', '9126625-6, ', 1000, 'images/dr-nazmul-diabetes.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '07.00PM to 09.00 PM', 'Popular Specialized Hospital Ltd', 'Sat,Tue,Fri'),
(4, 'Dr. AKM Sajedur Rahman', 'Medicine Specialists', 'Dr. AKM Sajedur Rahman\r\n\r\nQualifications:MBBS, BCS (Health), MD (Internal Medicine)\r\nAssistant Professor \r\nInstitute: Comilla Medical College,Comilla. \r\nDepartment Name:Medicine', 'akm.sknff@gmail.com', '867473294', 1500, 'images/Medicine Specialists.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '07.00PM to 09.00 PM', 'Popular Specialized Hospital Ltd', 'Sat,Mon,Fri'),
(5, 'Dr. Mohammad Abdur Rahman', 'Medicine Specialists', ':MBBS, BCS (Health), FCP\r\nLanguage Spoken: Bangla, English \r\nDesignation: Assistant Professor \r\nInstitute: Shaheed Suhrawardy Medical College & Hospital \r\n', 'abdur.rahman121@gmail.com', '7493472', 800, 'images/Neurologists.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '07.00PM to 09.00 PM', 'United Hospital Limited', 'Sat,Tue,Fri'),
(6, 'Dr. Muhammad Abdullahel Kafi', 'Neurologists', '\r\n\r\nQualifications:MBBS, MCPS (Medicine), FCPS (Gastroenterology)\r\ndhaka medical Hospital \r\nDepartment Name:Gastroenterology', ' Kafia.hdd@gmail.com', '9126625-6, ', 1500, 'images/Allergists.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '04.00PM to 06.00 PM', 'Popular Specialized Hospital Ltd', 'Sun,Mon,Tue'),
(7, 'Prof. Dr. Md. Mohibul Aziz', 'Neurologists', '\r\nMBBS,FCPS, FRCS (Edinbonf)\r\nDesignation: Professor & Head of the Department \r\nranpur medical college and hospital', 'Aziz.khan@gmail.com', '6475833', 1200, 'images/Neurologists.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '04.00PM to 06.00 PM', 'United Hospital Limited', 'Sat,Mon,Fri'),
(8, 'Dr. Md. Towhidul Islam', 'Neurologists', 'Dr. Md. Towhidul Islam\r\n\r\nQualifications:MBBS, FCPS, MS (Colorectal )\r\n \r\nDesignation: Consultant \r\n BSMMU :General Surgery', 'towhid>abid@gmail.com', '54325274', 1000, 'images/Medicine Specialists.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '04.00PM to 06.00 PM', 'Shahid Suhrawardy Hospital', 'Sun,Mon,Tue'),
(9, ' Dr. Farhana Dewan', 'Gynecologists', 'Qualifications:MBBS, FCPS (Gynae &Obs)\r\n Professor & Head of the Department \r\nInstitute: Ibn Sina Medical College Hospital \r\nGynae & Obs', 'farhna.23rahima@gmail.com', '15364757', 800, 'images/dr-nazmul-diabetes.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '04.00PM to 06.00 PM', 'United Hospital Limited', 'Sat,Tue,Fri'),
(10, 'rubina akter', 'Gynecologists', 'MBBS, MCPS, FCPS (Gynae &Obs)\r\nDesignation: Associate Professor \r\nInstitute: Ibn Sina Medical College Hospital \r\n', 'rubina.akter@gmail.com', '76849393', 1200, 'images/Dermatologists.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '08.00PM to 011.00 PM', 'Islami Bank Hospital', 'Sun,Mon,Tue'),
(11, 'Dr. Anzuman Ara (Bulu)\r\n', 'Gynecologists\r\n', '\r\n\r\nQualifications:MBBS MCPS (Gynae & Obs),DMSU (SU)\r\n', 'anzumanar@gmail.com', '55637282', 1000, 'images/Medicine Specialists.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '08.00PM to 011.00 PM', 'Square Hospital Ltd', 'Sun,Mon,Wed'),
(12, 'labib abir ', 'Oncologists', 'MBBS, FCPS (Gynae &Obs)\r\ndinajpur medical college and hospital', 'labib.abir@gmail.com', '940382371', 1000, 'images/Allergists.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '08.00PM to 011.00 PM', 'Shahid Suhrawardy Hospital', 'Sun,Mon,Wed'),
(13, 'hamid ahamed', 'Oncologists\r\n', 'dhaka medical college\r\n(mbbs, fbps,antrp)\r\nAssistant Professor \r\n  ', 'hamid.rashid@gmail.com', '18473722', 1500, 'images/Medicine Specialists.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '08.00PM to 011.00 PM', 'Islami Bank Hospital', 'Sun,Mon,Wed'),
(14, 'mehjabin alam', 'Oncologists\r\n', 'MBBS, MS (Ortho) Fellow (England)\r\nOrthopaedic & Traumatology ', 'mehjabin.alam12@gmail.com', '017336262', 1500, 'images/dr-nazmul-diabetes.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '09.00AM to 012.00 PM', 'Ad-Din Hospital', 'Sat,Tue'),
(15, 'rajib kabir', 'Dermatologists', 'MBBS D-Ortho, MS (Ortho)\r\nSpecialty: Orthopaedics ( Replacement Surgery & Arthoscopic Surgery ', 'rajib.kabir', '16527372', 1400, 'images/Neurologists.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '09.00AM to 012.00 PM', 'Ad-Din Hospital', 'Mon,Wed'),
(16, 'samia raima', 'Dermatologists', 'MBBS, D-Ortho (hspc in England )\r\n \r\nDesignation: Consultant \r\n', 'samia.raima@gmail.com', '0168392842', 1000, 'images/Dermatologists.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '09.00AM to 012.00 PM', 'Ad-Din Hospital', 'Mon,Wed,Thu'),
(17, 'Prof. Lt.Colonel (Rtd) Dr. Md. Abdullah Hel Kafi', 'Dermatologists', 'MBBS, MCPS, FCPS (ENT)\r\n ENT & Head Neck Surgeon ', 'Abdullah.alim@gmail.com', '01989838372', 1200, 'images/Allergists.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '09.00AM to 012.00 PM', 'Appolo Hospital', 'Mon,Wed,Thu'),
(18, 'sumit chakrabaty', 'Internists', 'MBBS, FCPS (ENT), canada-fpsc\r\nsaheed shawrowardi medical college\r\n', 'sumit@gmail.com', '019373634', 1500, 'images/Medicine Specialists.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '06.00PM to 10.00 PM', 'Appolo Hospital', 'Sat,Sun'),
(19, 'sadekur rahman', 'Dermatologists', ':MBBS, FCPS (ENT), canada-fpsc\r\nsaheed shawrowardi medical college\r\n', 'sadekur.123@gmail.com', '27525252', 1500, 'images/Dermatologists.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '06.00PM to 10.00 PM', 'Appolo Hospital', 'Mon,Thu,Fri'),
(20, 'Prof. Dr. Md. Mobashir Khalil\r\n', 'Internists', 'MBBS, MD (Cardiology)\r\n\r\nDesignation: Professor & Head of the Department \r\nInstitute: Holy Family Red Crescent Medical College,Dhaka \r\nDepartment Name:Cardiology', 'mobashir12khalil@gmail.com', '0163524113', 1500, 'images/Neurologists.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '05.00PM to 09.00 PM', 'United Hospital Limited', 'Sun,Mon,Tue'),
(21, 'Dr.Neena Islam', 'Internists', 'MBBS,FCPS (Medicine),MD(Cardiology)\r\n  \r\nDesignation: Associate Professor \r\nInstitute: National Centre for Control of Rheumatic Fever & Heart Disease \r\n', 'neena.alim@gmail.com', '017362533', 1000, 'images/Allergists.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '06.00PM to 08.00 PM', 'Appolo Hospital', 'Wed,Fri'),
(22, 'Dr. Muhammad Masudur Rahman', 'Pathologists', '\r\n\r\nQualifications:MBBS, BCS (Health), MD (Neuro Medicine)\r\nAssistant Professor National Institute of Neuro Science & Hospital \r\n', ' Masudur.alom@gmail.com', '9126625-6, ', 1200, 'images/Medicine Specialists.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '04.00PM to 08.00 PM', 'Ibn-Sina Medical College & Hospital', 'Sat,Fri'),
(23, 'Prof.Dr. Md. Khoybor Ali', 'Pathologists', 'Qualifications:MBBS, DCH, FCPS (Paed)\r\n \r\nProfessor & Head of the Department \r\nDepartment Name:paediatric', 'md.khoybor@gmail.com', '24124162', 800, 'images/Neurologists.jpg', 'Fellow-National Heart Centre, Singapore, Fellow-Escorts Hospital, New Delhi India, Specialist in Intravascular Ultrasound. Dr. Zaman received SAARC Cardiology hands on Fellowship in Interventional cardiology at Escorts Heart institute and research centre (EHIR&C), New Delhi, India for 01(one) year in June 2006. Subsequently he was selected for another 01(one) year hands on Fellowship program in Interventional Cardiology at National Heart Centre, Singapore and received the fellowship award in July 2007. He has successfully completed Rotablation, Intravascular ultrasound Pressure wire and peripheral stenting course. He also gained and experienced a numerous number of invasive and clinical training and observatory fellowship and visited USA, Canada, France, England, Japan, Italy, Sweden, Hong Kong, China, Jamaica, Costarica, Malaysia, Thailand, India, Pakistan and Nepal. Dr Zaman has published articles and presented cases at numerous National and international conferences. He has vast experiences of 10 years to perform invasive & interventional and complex diagnostic and therapeutic procedures independently & confidently. He is regular Faculty / Guest Speaker and participated in a large number of International workshops, seminars, symposiums both home and abroad that has enriched his decision making capacity, professional skills and care giving attitude to an international level for long time working experience in foreign hospitals. For last 10 years he is performing highest number of complex bifurcation, CTOs, primary PCI, Renal & Peripheral Angioplasties at SQUARE Hospital.', '07.00PM to 011.00 PM', 'Square Hospital Ltd', 'Sat,Sun,Wed');

-- --------------------------------------------------------

--
-- Table structure for table `patient`
--

CREATE TABLE `patient` (
  `Id` int(11) NOT NULL,
  `Name` varchar(100) NOT NULL,
  `Date` date NOT NULL,
  `History` text NOT NULL,
  `Email` varchar(100) NOT NULL,
  `Phone` varchar(20) NOT NULL,
  `Disease` varchar(50) NOT NULL,
  `Appoint_Doctor` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `patient`
--

INSERT INTO `patient` (`Id`, `Name`, `Date`, `History`, `Email`, `Phone`, `Disease`, `Appoint_Doctor`) VALUES
(1, 'adklak', '2018-09-04', 'sad;\'ads', 'asm@mail.com', '12345', 'Allergists', '');

-- --------------------------------------------------------

--
-- Table structure for table `time_slot`
--

CREATE TABLE `time_slot` (
  `Id` int(11) NOT NULL,
  `Time` varchar(20) NOT NULL,
  `Day` varchar(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `password`) VALUES
(1, 'maruf ahamed', 'maruf@mail.com', '123456');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `diagonistic_test`
--
ALTER TABLE `diagonistic_test`
  ADD PRIMARY KEY (`Id`);

--
-- Indexes for table `doctor`
--
ALTER TABLE `doctor`
  ADD PRIMARY KEY (`Id`);

--
-- Indexes for table `patient`
--
ALTER TABLE `patient`
  ADD PRIMARY KEY (`Id`);

--
-- Indexes for table `time_slot`
--
ALTER TABLE `time_slot`
  ADD PRIMARY KEY (`Id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `diagonistic_test`
--
ALTER TABLE `diagonistic_test`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `doctor`
--
ALTER TABLE `doctor`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=24;

--
-- AUTO_INCREMENT for table `patient`
--
ALTER TABLE `patient`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `time_slot`
--
ALTER TABLE `time_slot`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
